/* < Include ::: Header > */
#include "control_struct_menu.h"

/* < Declaracion :::  Variables Menus CAN... > */
const xIconsMenu_t __attribute__((space(auto_psv))) MainCANMenu[] = {
    {.pxNextMenu = &SerialCANCtrl, .pxIcon = Icon_MenuSingleKey, .StringText[0] = "PGM Serial", .StringText[1] = ""},
    {.pxNextMenu = &PasswordCANCtrl, .pxIcon = Icon_MenuDoubleKey, .StringText[0] = "Password", .StringText[1] = ""},
    {.pxNextMenu = &ParametersCANCtrl, .pxIcon = Icon_MenuParammeters, .StringText[0] = "Parameters", .StringText[1] = ""},
    {.pxNextMenu = &StatusDoorCANCtrl, .pxIcon = Icon_MenuDoorStatus, .StringText[0] = "DoorSelect", .StringText[1] = ""},
    {.pxNextMenu = &ControlsCANCtrl, .pxIcon = Icon_MenuControls, .StringText[0] = "Controls", .StringText[1] = ""},
    {.pxNextMenu = &TimesCANCtrl, .pxIcon = Icon_MenuTimes, .StringText[0] = "Times", .StringText[1] = ""},
    {.pxNextMenu = &InputsCANCtrl, .pxIcon = Icon_MenuInputs, .StringText[0] = "Inputs", .StringText[1] = ""},
    {.pxNextMenu = &OutputsCANCtrl, .pxIcon = Icon_MenuOutpus, .StringText[0] = "Outpus", .StringText[1] = ""},
    {.pxNextMenu = NULL, .pxIcon = Icon_MenuErrors, .StringText[0] = "Errors ", .StringText[1] = ""},
    {.pxNextMenu = NULL, .pxIcon = Icon_MenuStatus, .StringText[0] = "Status", .StringText[1] = ""},
    {.pxNextMenu = NULL, .pxIcon = Icon_MenuManeuver, .StringText[0] = "Maneuver", .StringText[1] = ""},
    {.pxNextMenu = NULL, .pxIcon = Icon_MenuSettings, .StringText[0] = "Settings", .StringText[1] = ""}
};

const xSerialMenu_t __attribute__((space(auto_psv))) SerialCANMenu[] = {
    {.StringText[0] = "Read(X)  Prog(A)", .StringText[1] = "", .pxVariable = (void*) xControls.Board.Serial.Ascii, .TypeVariable = TYPE_VARIABLE_SERIAL, .SizeVariable = sizeof (xControls.Board.Serial.Ascii), .LengthOptions = sizeof (xControls.Board.Serial.Ascii)},
    /* < ------------------------------------------------------------------ > */
    {.pxVariable = &xControls.Board.Serial.Ascii, .SizeVariable = sizeof (xControls.Board.Serial.Ascii), .TypeVariable = TYPE_VARIABLE_FUNCTION_A},
    {.pxVariable = &xControls.Board.Serial.Ascii, .SizeVariable = sizeof (xControls.Board.Serial.Ascii), .TypeVariable = TYPE_VARIABLE_FUNCTION_B},
    {.pxVariable = &xControls.Board.Serial.Ascii, .SizeVariable = sizeof (xControls.Board.Serial.Ascii), .TypeVariable = TYPE_VARIABLE_FUNCTION_C},
};

const xSerialMenu_t __attribute__((space(auto_psv))) PasswordCANMenu[] = {
    {.pxIcon = Icon_Key, .pxVariable = (void*) xControls.Board.Serial.Ascii, .TypeVariable = TYPE_VARIABLE_SERIAL, .LengthOptions = sizeof (xControls.Board.Serial.Ascii)},
    {.StringText[0] = "Save(X)", .StringText[1] = "", .pxIcon = Icon_Key, .pxVariable = (void*) xControls.Board.Password.Ascii, .TypeVariable = TYPE_VARIABLE_SERIAL, .LengthOptions = sizeof (xControls.Board.Password.Ascii)},
    /* < ------------------------------------------------------------------ > */
    {.pxVariable = &xControls.Board.Serial.Ascii, .SizeVariable = sizeof (xControls.Board.Serial.Ascii), .TypeVariable = TYPE_VARIABLE_FUNCTION_A},
    {.pxVariable = &xControls.Board.Password.Ascii, .SizeVariable = sizeof (xControls.Board.Password.Ascii), .TypeVariable = TYPE_VARIABLE_FUNCTION_B}
};

const xListsMenu_t __attribute__((space(auto_psv))) ParametersCANMenu[] = {
    {.StringText[0] = "TypeDoor", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Tipo_Puerta, .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 4, .pxStringOptions[0] = "AUT", .pxStringOptions[1] = "SEM", .pxStringOptions[2] = "BAT", .pxStringOptions[3] = "MAN"},
    {.StringText[0] = "TypClose", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Gestion_Cierre_Puerta, .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 3, .pxStringOptions[0] = "AUT", .pxStringOptions[1] = "CAL", .pxStringOptions[2] = "BUT"},
    {.StringText[0] = "CtlSpeed", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Gestion_Velocidad_Inversor, .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 2, .pxStringOptions[0] = "SIM", .pxStringOptions[1] = "DOU"},
    {.StringText[0] = "ModHidra", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Modo_Hidrahulico, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "SenHidra", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Sensor_Hidrahulico, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "SenseUPS", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Sensor_Unit_Power_Suply, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "ServiKEY", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Sensor_Llave_Servicio, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "BlockKEY", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Sensor_Llave_Bloqueo, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "DelCalls", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Borrado_Llamadas, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "TypCalls", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Gestion_Llamadas, .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 4, .pxStringOptions[0] = "SIM", .pxStringOptions[1] = "DUA", .pxStringOptions[2] = "COL", .pxStringOptions[3] = "SEL"},
    {.StringText[0] = "CtlGroup", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Gestion_Grupal, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "CtlSlave", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Modo_Master_Slave, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "NumSlave", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Gestion_Numero_Slaves, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 8},
    {.StringText[0] = "AuxSlave", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Modo_Auxiliar_Master, .TypeVariable = TYPE_VARIABLE_BOOL, .SizeVariable = sizeof (uint1_t), .LengthOptions = 2},
    {.StringText[0] = "PriSlave", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Parametro.Prioridad_Slave, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 8},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Options-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.pxIcon = Icon_Return, .StringText[0] = " Read All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Parametro, .SizeVariable = sizeof (xSystemParametersCAN.Parametro), .TypeFunction = TYPE_VARIABLE_FUNCTION_A},
    {.pxIcon = Icon_Reset, .StringText[0] = " Clear All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Parametro, .SizeVariable = sizeof (xSystemParametersCAN.Parametro), .TypeFunction = TYPE_VARIABLE_FUNCTION_B},
    {.pxIcon = Icon_Saved, .StringText[0] = " Save All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Parametro, .SizeVariable = sizeof (xSystemParametersCAN.Parametro), .TypeFunction = TYPE_VARIABLE_FUNCTION_C},
};

const xListsMenu_t __attribute__((space(auto_psv))) DoorStatusMenuCAN[] = {
    {.StringText[0] = "Floor 01", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x00], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 02", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x01], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 03", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x02], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 04", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x03], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 05", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x04], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 06", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x05], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 07", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x06], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 08", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x07], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 09", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x08], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 10", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x09], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 11", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x0A], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 12", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x0B], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 13", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x0C], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 14", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x0D], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 15", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x0E], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 16", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x0F], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 17", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x10], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 18", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x11], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 19", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x12], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 20", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x13], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 21", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x14], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 22", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x15], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 23", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x16], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 24", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x17], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 25", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x18], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 26", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x19], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 27", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x1A], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 28", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x1B], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 29", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x1C], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 30", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x1D], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 31", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x1E], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    {.StringText[0] = "Floor 32", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Puertas.Estado[0x1F], .TypeVariable = TYPE_VARIABLE_TEXT, .SizeVariable = sizeof (uint8_t), 3, .pxStringOptions[0] = "ONE", .pxStringOptions[1] = "TWO", .pxStringOptions[2] = "BOT"},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Options-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.pxIcon = Icon_Return, .StringText[0] = " Read All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Puertas, .SizeVariable = sizeof (xSystemParametersCAN.Puertas), .TypeFunction = TYPE_VARIABLE_FUNCTION_A},
    {.pxIcon = Icon_Reset, .StringText[0] = " Clear All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Puertas, .SizeVariable = sizeof (xSystemParametersCAN.Puertas), .TypeFunction = TYPE_VARIABLE_FUNCTION_B},
    {.pxIcon = Icon_Saved, .StringText[0] = " Save All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Puertas, .SizeVariable = sizeof (xSystemParametersCAN.Puertas), .TypeFunction = TYPE_VARIABLE_FUNCTION_C},
};

const xListsMenu_t __attribute__((space(auto_psv))) ControlsMenuCAN[] = {
    {.StringText[0] = "MaxFloor", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Control.Numero_Max_Pisos, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Control.Numero_Max_Pisos), .LengthOptions = 32},
    {.StringText[0] = "MaxVault", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Control.Numero_Max_Sotanos, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Control.Numero_Max_Sotanos), .LengthOptions = 8},
    {.StringText[0] = "RetCabin", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Control.Numero_Retorno_Cabina, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Control.Numero_Retorno_Cabina), .LengthOptions = 32},
    {.StringText[0] = "RetFire", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Control.Numero_Retorno_Bombero, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Control.Numero_Retorno_Bombero), .LengthOptions = 32},
    {.StringText[0] = "MaxT", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Control.Numero_Limite_Viajes, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Control.Numero_Limite_Viajes), .LengthOptions = 9999999UL},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Options-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.pxIcon = Icon_Return, .StringText[0] = " Read All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Control, .SizeVariable = sizeof (xSystemParametersCAN.Control), .TypeFunction = TYPE_VARIABLE_FUNCTION_A},
    {.pxIcon = Icon_Reset, .StringText[0] = " Clear All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Control, .SizeVariable = sizeof (xSystemParametersCAN.Control), .TypeFunction = TYPE_VARIABLE_FUNCTION_B},
    {.pxIcon = Icon_Saved, .StringText[0] = " Save All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Control, .SizeVariable = sizeof (xSystemParametersCAN.Control), .TypeFunction = TYPE_VARIABLE_FUNCTION_C},
};

const xListsMenu_t __attribute__((space(auto_psv))) TimesMenuCAN[] = {
    {.StringText[0] = "StarPost", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Start_Post, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Start_Post), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "StarGoUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Reconocimiento_Subiendo, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Reconocimiento_Subiendo), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "StarGoMd", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Reconocimiento_Intermedio, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Reconocimiento_Intermedio), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "StarGoDw", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Reconocimiento_Bajando, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Reconocimiento_Bajando), UINT8_MAX},
    {.StringText[0] = "RevlGoUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Renivelacion_Cabina_Subiendo, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Renivelacion_Cabina_Subiendo), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "RevlGoDw", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Renivelacion_Cabina_Bajando, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Renivelacion_Cabina_Bajando), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "ButClose", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Atender_Boton_Cerrar, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Atender_Boton_Cerrar), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "ButUnbar", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Atender_Boton_Abrir, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Atender_Boton_Abrir), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "DoorClos", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Accion_Cerrar_Puerta, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Accion_Cerrar_Puerta), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "RetCabin", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Retorno_Cabina, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Retorno_Cabina), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "TrlCabin", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Viaje_Entre_Pisos_Cabina, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Viaje_Entre_Pisos_Cabina), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "LedCabin", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Apagar_Luz_Cabina, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Apagar_Luz_Cabina), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "SonCabin", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Inicio_Sonido_Cabina, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Inicio_Sonido_Cabina), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "LmtSpeed", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Chequeo_Limites_Velocidad, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Chequeo_Limites_Velocidad), .LengthOptions = UINT8_MAX},
    {.StringText[0] = "StarTrav", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Incio_Viaje_Cabina, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Incio_Viaje_Cabina), .LengthOptions = UINT16_MAX},
    {.StringText[0] = "StopTrav", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Tiempo.Final_Viaje_Cabina, .TypeVariable = TYPE_VARIABLE_INT, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo.Final_Viaje_Cabina), .LengthOptions = UINT16_MAX},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Options-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.pxIcon = Icon_Return, .StringText[0] = " Read All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Tiempo, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo), .TypeFunction = TYPE_VARIABLE_FUNCTION_A},
    {.pxIcon = Icon_Reset, .StringText[0] = " Clear All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Tiempo, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo), .TypeFunction = TYPE_VARIABLE_FUNCTION_B},
    {.pxIcon = Icon_Saved, .StringText[0] = " Save All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Tiempo, .SizeVariable = sizeof (xSystemParametersCAN.Tiempo), .TypeFunction = TYPE_VARIABLE_FUNCTION_C},
};

const xListsMenu_t __attribute__((space(auto_psv))) InputsMenuCAN[] = {
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Senses-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "Pulses", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    {.StringText[0] = "Nivel", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "SpeedHigh", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "SpeedLow", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "Relevel", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "UPS", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "Break", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "Aux", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSenses.RegisterSenses, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x80},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Securities-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "First", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    {.StringText[0] = "Second", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "DoorHall", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "DoorCabin", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "DoorSwing", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "ReviewCtrl", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "ReviewUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "ReviewDw", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Input.LogicSecurities.RegisterSecurties, .TypeVariable = TYPE_VARIABLE_BIT_TEXT, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x80},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Options-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.pxIcon = Icon_Return, .StringText[0] = " Read All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Input, .SizeVariable = sizeof (xSystemParametersCAN.Input), .TypeFunction = TYPE_VARIABLE_FUNCTION_A},
    {.pxIcon = Icon_Reset, .StringText[0] = " Clear All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Input, .SizeVariable = sizeof (xSystemParametersCAN.Input), .TypeFunction = TYPE_VARIABLE_FUNCTION_B},
    {.pxIcon = Icon_Saved, .StringText[0] = " Save All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Input, .SizeVariable = sizeof (xSystemParametersCAN.Input), .TypeFunction = TYPE_VARIABLE_FUNCTION_C},
};

const xListsMenu_t __attribute__((space(auto_psv))) OutputsMenuCAN[] = {
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Stop-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "1.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicStop.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "1.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicStop.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "1.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicStop.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "1.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicStop.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "1.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicStop.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "1.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicStop.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "1.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicStop.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Relevel Up-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "2.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "2.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "2.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "2.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "2.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "2.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "2.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Review Up-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "3.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "3.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "3.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "3.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "3.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "3.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "3.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Middle1 Up-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "4.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "4.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "4.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "4.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "4.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "4.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "4.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Middle2 Up-", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "5.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "5.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "5.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "5.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "5.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "5.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "5.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Nominal Up-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "6.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "6.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "6.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "6.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "6.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "6.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "6.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalArriba.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Relevel Dw-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "7.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "7.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "7.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "7.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "7.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "7.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "7.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNivelacionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Review Dw-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "8.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "8.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "8.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "8.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "8.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "8.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "8.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicRevisionBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Middle1 Dw-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "9.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "9.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "9.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "9.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "9.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "9.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    {.StringText[0] = "9.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaUnoBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Middle2 Dw-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "A.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "A.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "A.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "A.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "A.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "A.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "A.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicIntermediaDosBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Nominal Dw-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.StringText[0] = "B.Leveling", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x40},
    {.StringText[0] = "B.Review", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x20},
    {.StringText[0] = "B.Middle1", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x10},
    {.StringText[0] = "B.Middle2", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x08},
    {.StringText[0] = "B.Nominal", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x04},
    {.StringText[0] = "B.WayUp", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x02},
    {.StringText[0] = "B.WayDown", .StringText[1] = "", .TypeFunction = TYPE_VARIABLE_FUNCTION_D, .pxVariable = (void*) &xSystemParametersCAN.Outputs.LogicNominalBajando.RegisterRelays, .TypeVariable = TYPE_VARIABLE_BIT_BOOL, .SizeVariable = sizeof (uint8_t), .LengthOptions = 0x01},
    /* < ------------------------------------------------------------------ > */
    {.StringText[0] = "-Options-", .StringText[1] = "", .TypeVariable = TYPE_VARIABLE_TITLE},
    {.pxIcon = Icon_Return, .StringText[0] = " Read All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Outputs, .SizeVariable = sizeof (xSystemParametersCAN.Outputs), .TypeFunction = TYPE_VARIABLE_FUNCTION_A},
    {.pxIcon = Icon_Reset, .StringText[0] = " Clear All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Outputs, .SizeVariable = sizeof (xSystemParametersCAN.Outputs), .TypeFunction = TYPE_VARIABLE_FUNCTION_B},
    {.pxIcon = Icon_Saved, .StringText[0] = " Save All", .StringText[1] = "", .pxVariable = &xSystemParametersCAN.Outputs, .SizeVariable = sizeof (xSystemParametersCAN.Outputs), .TypeFunction = TYPE_VARIABLE_FUNCTION_C},
};

/* < Declaracion ::: Variables Controles CAN... > */
xControlMenu_t MainCANCtrl = {
    .pxCurrentMenu = MainCANMenu, .xType = TYPE_MENU_ICONS, .xLength = (sizeof (MainCANMenu) / sizeof (xIconsMenu_t))
};

xControlMenu_t SerialCANCtrl = {
    .pxCurrentMenu = SerialCANMenu, .StringText[0] = "SerialBoard", .StringText[1] = "", .xType = TYPE_MENU_SERIAL, .pxFunctionA = vReadParametersCAN, .pxFunctionB = vClearParametersCAN, .pxFunctionC = vSavedParametersCAN
};

xControlMenu_t PasswordCANCtrl = {
    .pxCurrentMenu = PasswordCANMenu, .StringText[0] = "Password", .StringText[1] = "", .xType = TYPE_MENU_PASSWORD, .pxFunctionA = vSendSerialPassword, .pxFunctionB = vSavedParametersCAN
};

xControlMenu_t ParametersCANCtrl = {
    .pxCurrentMenu = ParametersCANMenu, .StringText[0] = "Parameters", .StringText[1] = "", .xType = TYPE_MENU_LIST, .xLength = (sizeof (ParametersCANMenu) / sizeof (xListsMenu_t)), .pxFunctionA = vReadParametersCAN, .pxFunctionB = vClearParametersCAN, .pxFunctionC = vSavedParametersCAN, .pxFunctionD = vSaveSingleParametersCAN, .pxFunctionE = vReadSingleParametersCAN
};

xControlMenu_t StatusDoorCANCtrl = {
    .pxCurrentMenu = DoorStatusMenuCAN, .StringText[0] = "StatusDoor", .StringText[1] = "", .xType = TYPE_MENU_LIST, .xLength = (sizeof (DoorStatusMenuCAN) / sizeof (xListsMenu_t)), .pxFunctionA = vReadParametersCAN, .pxFunctionB = vClearParametersCAN, .pxFunctionC = vSavedParametersCAN, .pxFunctionD = vSaveSingleParametersCAN, .pxFunctionE = vReadSingleParametersCAN
};

xControlMenu_t ControlsCANCtrl = {
    .pxCurrentMenu = ControlsMenuCAN, .StringText[0] = "Controls", .StringText[1] = "", .xType = TYPE_MENU_LIST, .xLength = (sizeof (ControlsMenuCAN) / sizeof (xListsMenu_t)), .pxFunctionA = vReadParametersCAN, .pxFunctionB = vClearParametersCAN, .pxFunctionC = vSavedParametersCAN, .pxFunctionD = vSaveSingleParametersCAN, .pxFunctionE = vReadSingleParametersCAN
};

xControlMenu_t TimesCANCtrl = {
    .pxCurrentMenu = TimesMenuCAN, .StringText[0] = "Times", .StringText[1] = "", .xType = TYPE_MENU_LIST, .xLength = (sizeof (TimesMenuCAN) / sizeof (xListsMenu_t)), .pxFunctionA = vReadParametersCAN, .pxFunctionB = vClearParametersCAN, .pxFunctionC = vSavedParametersCAN, .pxFunctionD = vSaveSingleParametersCAN, .pxFunctionE = vReadSingleParametersCAN
};

xControlMenu_t InputsCANCtrl = {
    .pxCurrentMenu = InputsMenuCAN, .StringText[0] = "Inputs", .StringText[1] = "", .xType = TYPE_MENU_LIST, .xLength = (sizeof (InputsMenuCAN) / sizeof (xListsMenu_t)), .pxFunctionA = vReadParametersCAN, .pxFunctionB = vClearParametersCAN, .pxFunctionC = vSavedParametersCAN, .pxFunctionD = vSaveSingleParametersCAN, .pxFunctionE = vReadSingleParametersCAN
};

xControlMenu_t OutputsCANCtrl = {
    .pxCurrentMenu = OutputsMenuCAN, .StringText[0] = "Outputs", .StringText[1] = "", .xType = TYPE_MENU_LIST, .xLength = (sizeof (OutputsMenuCAN) / sizeof (xListsMenu_t)), .pxFunctionA = vReadParametersCAN, .pxFunctionB = vClearParametersCAN, .pxFunctionC = vSavedParametersCAN, .pxFunctionD = vSaveSingleParametersCAN, .pxFunctionE = vReadSingleParametersCAN
};

